const t = () => {
  return (
    <div
      className="
      disabled:bg-shadedColor
      inline-block
      w-full
      flex-grow
      rounded
      border
      border-neutral-400
      bg-transparent
      px-3
      py-1.5
      text-inherit
      shadow-inner
      hover:border-brandColor/50
      hover:outline-none
      hover:ring-2
      hover:ring-brandColor/20
      hover:ring-offset-2
      focus:border-brandColor
      focus:outline-none
      focus:ring-2
      focus:ring-brandColor/20
      focus:ring-offset-2
    "
    />
  );
};
