export const HEART_LOSS_ANIMATION_DURATION_MS = 1000
export const HEART_LOSS_ANIMATION_DURATION_SECONDS =
  HEART_LOSS_ANIMATION_DURATION_MS / 1000
export const HEART_LOSS_ANIMATION_ROTATION_DEGREES = 6
export const HEART_LOSS_ANIMATION_SCALE = 5
export const HEART_LOSS_ANIMATION_Y_PERCENT = 100
export const HEART_LOSS_ANIMATION_COLOR = 'var(--color-red-500)'
export const HEART_LOSS_EXIT_DURATION_MS = 300
export const HEART_LOSS_EXIT_DURATION_SECONDS =
  HEART_LOSS_EXIT_DURATION_MS / 1000
export const HEART_LOSS_EXIT_OPACITY = 0.5
export const HEART_LOSS_EXIT_ROTATION_DEGREES = 360
export const HEART_LOSS_EXIT_SCALE = 0.75
export const HEART_LOSS_EXIT_Y_PERCENT = 0

export const HEART_LOSS_ANIMATION_CLASS_NAME = `
  text-red-500
  duration-1000
  translate-y-full
  rotate-6
  scale-[5]
`
